export const clothesData = [
  {
    id: 1,
    name: "Men's Cotton T-Shirt",
    price: 499,
    category: "T-Shirts",
    gender: "male",
    rating: 4.5,
    size: ["S", "M", "L", "XL"],
    color: "Black",
    image: "https://images.pexels.com/photos/1002638/pexels-photo-1002638.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 2,
    name: "Men's Slim Fit Jeans",
    price: 1499,
    category: "Jeans",
    gender: "male",
    rating: 4.3,
    size: ["30", "32", "34", "36"],
    color: "Dark Blue",
    image: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 3,
    name: "Men's Formal Shirt",
    price: 899,
    category: "Shirts",
    gender: "male",
    rating: 4.4,
    size: ["M", "L", "XL"],
    color: "White",
    image: "https://images.pexels.com/photos/428340/pexels-photo-428340.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 4,
    name: "Women's Sports Bra",
    price: 599,
    category: "Sportwear",
    gender: "female",
    rating: 4.6,
    size: ["S", "M", "L"],
    color: "Grey",
    image: "https://images.pexels.com/photos/3768913/pexels-photo-3768913.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 5,
    name: "Men's Graphic T-Shirt",
    price: 699,
    category: "T-Shirts",
    gender: "male",
    rating: 4.1,
    size: ["M", "L", "XL"],
    color: "Navy Blue",
    image: "https://images.pexels.com/photos/1002640/pexels-photo-1002640.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 6,
    name: "Women's Joggers",
    price: 1099,
    category: "Sportwear",
    gender: "female",
    rating: 4.3,
    size: ["S", "M", "L", "XL"],
    color: "Olive Green",
    image: "https://images.pexels.com/photos/6311612/pexels-photo-6311612.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 7,
    name: "Men's Stretch Jeans",
    price: 1599,
    category: "Jeans",
    gender: "male",
    rating: 4.2,
    size: ["30", "32", "34"],
    color: "Black",
    image: "https://images.pexels.com/photos/7679728/pexels-photo-7679728.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 8,
    name: "Men's Casual Shirt",
    price: 999,
    category: "Shirts",
    gender: "male",
    rating: 4.0,
    size: ["M", "L", "XL"],
    color: "Blue",
    image: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 9,
    name: "Kids Printed T-Shirt",
    price: 399,
    category: "T-Shirts",
    gender: "kids",
    rating: 4.5,
    size: ["XS", "S", "M"],
    color: "Yellow",
    image: "https://images.pexels.com/photos/3661332/pexels-photo-3661332.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 10,
    name: "Kids Blue Jeans",
    price: 799,
    category: "Jeans",
    gender: "kids",
    rating: 4.6,
    size: ["22", "24", "26"],
    color: "Light Blue",
    image: "https://images.pexels.com/photos/1648377/pexels-photo-1648377.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 11,
    name: "Women's Oversized T-Shirt",
    price: 749,
    category: "T-Shirts",
    gender: "female",
    rating: 4.2,
    size: ["S", "M", "L"],
    color: "Lavender",
    image: "https://images.pexels.com/photos/6311605/pexels-photo-6311605.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 12,
    name: "Unisex White Sports T-Shirt",
    price: 599,
    category: "Sportwear",
    gender: "unisex",
    rating: 4.4,
    size: ["M", "L", "XL"],
    color: "White",
    image: "https://images.pexels.com/photos/3763870/pexels-photo-3763870.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 13,
    name: "Women's High-Waist Jeans",
    price: 1399,
    category: "Jeans",
    gender: "female",
    rating: 4.6,
    size: ["28", "30", "32"],
    color: "Light Blue",
    image: "https://images.pexels.com/photos/7679872/pexels-photo-7679872.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 14,
    name: "Kids Hoodie - Red",
    price: 899,
    category: "Sportwear",
    gender: "kids",
    rating: 4.7,
    size: ["S", "M", "L"],
    color: "Red",
    image: "https://images.pexels.com/photos/189857/pexels-photo-189857.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 15,
    name: "Men's Running Shorts",
    price: 599,
    category: "Sportwear",
    gender: "male",
    rating: 4.2,
    size: ["M", "L", "XL"],
    color: "Navy",
    image: "https://images.pexels.com/photos/4553117/pexels-photo-4553117.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 16,
    name: "Men's Checked Shirt",
    price: 1099,
    category: "Shirts",
    gender: "male",
    rating: 4.5,
    size: ["M", "L", "XL"],
    color: "Green",
    image: "https://images.pexels.com/photos/1004014/pexels-photo-1004014.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 17,
    name: "Unisex Oversized Hoodie",
    price: 1599,
    category: "Sportwear",
    gender: "unisex",
    rating: 4.6,
    size: ["M", "L", "XL"],
    color: "Black",
    image: "https://images.pexels.com/photos/6311609/pexels-photo-6311609.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 18,
    name: "Girls Denim Jacket",
    price: 1199,
    category: "Shirts",
    gender: "kids",
    rating: 4.3,
    size: ["S", "M"],
    color: "Blue",
    image: "https://images.pexels.com/photos/1157305/pexels-photo-1157305.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 19,
    name: "Women's Sports Leggings",
    price: 899,
    category: "Sportwear",
    gender: "female",
    rating: 4.4,
    size: ["S", "M", "L"],
    color: "Black",
    image: "https://images.pexels.com/photos/4662438/pexels-photo-4662438.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 20,
    name: "Boy's Casual Shirt",
    price: 599,
    category: "Shirts",
    gender: "kids",
    rating: 4.1,
    size: ["S", "M"],
    color: "White & Blue",
    image: "https://images.pexels.com/photos/670720/pexels-photo-670720.jpeg?auto=compress&cs=tinysrgb&w=600",
  }
];
